spring:
  profiles: prd
  # 数据库链接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.223.74.120:3306/trade_management_db
    username: root
    password: Zdw@12345
    # 链接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 链接池初始化大小
      initial-size: 8
      # 最大活跃数
      max-active: 16
      # 最小空闲数
      min-idle: 1
      # 最大等待时间
      max-wait: 60000

#mybaits配置
mybatis:
  check-config-location: true
  # mybatis框架配置文件，对mybatis的生命周期起作用
  config-location: "classpath:trade-infrastructure/src/main/resources/mybatis/mybatis-config.xml"
    # 配置xml路径
    mapper-locations: "classpath:trade-data/src/main/resources/mapper/*Mapper.xml"
    # 配置model包路径
    type-aliases-package: "com.russellzhou.trade.data.entity.*"