package com.russellzhou.trade.data.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table inventory_info
 */
public class InventoryInfo {
    /**
     * Database Column Remarks:
     *   库存编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_info.inventory_id
     *
     * @mbg.generated
     */
    private String inventoryId;

    /**
     * Database Column Remarks:
     *   自增id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   spu编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_info.spu_id
     *
     * @mbg.generated
     */
    private Long spuId;

    /**
     * Database Column Remarks:
     *   sku编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_info.sku_id
     *
     * @mbg.generated
     */
    private Long skuId;

    /**
     * Database Column Remarks:
     *   当前数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_info.current_num
     *
     * @mbg.generated
     */
    private Integer currentNum;

    /**
     * Database Column Remarks:
     *   仓库编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_info.warehouse_code
     *
     * @mbg.generated
     */
    private String warehouseCode;

    /**
     * Database Column Remarks:
     *   仓库地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_info.warehouse_address
     *
     * @mbg.generated
     */
    private String warehouseAddress;

    /**
     * Database Column Remarks:
     *   价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_info.price
     *
     * @mbg.generated
     */
    private Integer price;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_info.is_del
     *
     * @mbg.generated
     */
    private Byte isDel;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_info.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_info.inventory_id
     *
     * @return the value of inventory_info.inventory_id
     *
     * @mbg.generated
     */
    public String getInventoryId() {
        return inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_info.inventory_id
     *
     * @param inventoryId the value for inventory_info.inventory_id
     *
     * @mbg.generated
     */
    public void setInventoryId(String inventoryId) {
        this.inventoryId = inventoryId == null ? null : inventoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_info.id
     *
     * @return the value of inventory_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_info.id
     *
     * @param id the value for inventory_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_info.spu_id
     *
     * @return the value of inventory_info.spu_id
     *
     * @mbg.generated
     */
    public Long getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_info.spu_id
     *
     * @param spuId the value for inventory_info.spu_id
     *
     * @mbg.generated
     */
    public void setSpuId(Long spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_info.sku_id
     *
     * @return the value of inventory_info.sku_id
     *
     * @mbg.generated
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_info.sku_id
     *
     * @param skuId the value for inventory_info.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_info.current_num
     *
     * @return the value of inventory_info.current_num
     *
     * @mbg.generated
     */
    public Integer getCurrentNum() {
        return currentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_info.current_num
     *
     * @param currentNum the value for inventory_info.current_num
     *
     * @mbg.generated
     */
    public void setCurrentNum(Integer currentNum) {
        this.currentNum = currentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_info.warehouse_code
     *
     * @return the value of inventory_info.warehouse_code
     *
     * @mbg.generated
     */
    public String getWarehouseCode() {
        return warehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_info.warehouse_code
     *
     * @param warehouseCode the value for inventory_info.warehouse_code
     *
     * @mbg.generated
     */
    public void setWarehouseCode(String warehouseCode) {
        this.warehouseCode = warehouseCode == null ? null : warehouseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_info.warehouse_address
     *
     * @return the value of inventory_info.warehouse_address
     *
     * @mbg.generated
     */
    public String getWarehouseAddress() {
        return warehouseAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_info.warehouse_address
     *
     * @param warehouseAddress the value for inventory_info.warehouse_address
     *
     * @mbg.generated
     */
    public void setWarehouseAddress(String warehouseAddress) {
        this.warehouseAddress = warehouseAddress == null ? null : warehouseAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_info.price
     *
     * @return the value of inventory_info.price
     *
     * @mbg.generated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_info.price
     *
     * @param price the value for inventory_info.price
     *
     * @mbg.generated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_info.is_del
     *
     * @return the value of inventory_info.is_del
     *
     * @mbg.generated
     */
    public Byte getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_info.is_del
     *
     * @param isDel the value for inventory_info.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Byte isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_info.create_time
     *
     * @return the value of inventory_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_info.create_time
     *
     * @param createTime the value for inventory_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_info.modify_time
     *
     * @return the value of inventory_info.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_info.modify_time
     *
     * @param modifyTime the value for inventory_info.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}