package com.russellzhou.trade.data.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sale_record_info
 */
public class SaleRecordInfo {
    /**
     * Database Column Remarks:
     *   销售记录编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.sale_record_id
     *
     * @mbg.generated
     */
    private String saleRecordId;

    /**
     * Database Column Remarks:
     *   自增id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   库存编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.inventory_id
     *
     * @mbg.generated
     */
    private String inventoryId;

    /**
     * Database Column Remarks:
     *   sku编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.sku_id
     *
     * @mbg.generated
     */
    private Long skuId;

    /**
     * Database Column Remarks:
     *   订单编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.order_no
     *
     * @mbg.generated
     */
    private String orderNo;

    /**
     * Database Column Remarks:
     *   销售平台
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.platform
     *
     * @mbg.generated
     */
    private Byte platform;

    /**
     * Database Column Remarks:
     *   出价金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.bid_price
     *
     * @mbg.generated
     */
    private Integer bidPrice;

    /**
     * Database Column Remarks:
     *   技术服务费
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.tech_service_fee
     *
     * @mbg.generated
     */
    private Integer techServiceFee;

    /**
     * Database Column Remarks:
     *   转账手续费
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.transfer_service_fee
     *
     * @mbg.generated
     */
    private Integer transferServiceFee;

    /**
     * Database Column Remarks:
     *   操作服务费
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.operate_service_fee
     *
     * @mbg.generated
     */
    private Integer operateServiceFee;

    /**
     * Database Column Remarks:
     *   卖家出资邮费
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.postage_fee
     *
     * @mbg.generated
     */
    private Integer postageFee;

    /**
     * Database Column Remarks:
     *   优惠金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.discount_fee
     *
     * @mbg.generated
     */
    private Integer discountFee;

    /**
     * Database Column Remarks:
     *   预估到手价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.estimate_price
     *
     * @mbg.generated
     */
    private Integer estimatePrice;

    /**
     * Database Column Remarks:
     *   实际到手金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.actual_price
     *
     * @mbg.generated
     */
    private Integer actualPrice;

    /**
     * Database Column Remarks:
     *   买家姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.buyer_name
     *
     * @mbg.generated
     */
    private String buyerName;

    /**
     * Database Column Remarks:
     *   买家收件地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.buyer_address
     *
     * @mbg.generated
     */
    private String buyerAddress;

    /**
     * Database Column Remarks:
     *   买家手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.buyer_mobile
     *
     * @mbg.generated
     */
    private String buyerMobile;

    /**
     * Database Column Remarks:
     *   快递承运公司
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.express_carrier
     *
     * @mbg.generated
     */
    private Byte expressCarrier;

    /**
     * Database Column Remarks:
     *   发货时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.send_time
     *
     * @mbg.generated
     */
    private Date sendTime;

    /**
     * Database Column Remarks:
     *   买家是否签收
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.has_received_flag
     *
     * @mbg.generated
     */
    private Byte hasReceivedFlag;

    /**
     * Database Column Remarks:
     *   买家签收时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.received_time
     *
     * @mbg.generated
     */
    private Date receivedTime;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.is_del
     *
     * @mbg.generated
     */
    private Byte isDel;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_record_info.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.sale_record_id
     *
     * @return the value of sale_record_info.sale_record_id
     *
     * @mbg.generated
     */
    public String getSaleRecordId() {
        return saleRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.sale_record_id
     *
     * @param saleRecordId the value for sale_record_info.sale_record_id
     *
     * @mbg.generated
     */
    public void setSaleRecordId(String saleRecordId) {
        this.saleRecordId = saleRecordId == null ? null : saleRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.id
     *
     * @return the value of sale_record_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.id
     *
     * @param id the value for sale_record_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.inventory_id
     *
     * @return the value of sale_record_info.inventory_id
     *
     * @mbg.generated
     */
    public String getInventoryId() {
        return inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.inventory_id
     *
     * @param inventoryId the value for sale_record_info.inventory_id
     *
     * @mbg.generated
     */
    public void setInventoryId(String inventoryId) {
        this.inventoryId = inventoryId == null ? null : inventoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.sku_id
     *
     * @return the value of sale_record_info.sku_id
     *
     * @mbg.generated
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.sku_id
     *
     * @param skuId the value for sale_record_info.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.order_no
     *
     * @return the value of sale_record_info.order_no
     *
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.order_no
     *
     * @param orderNo the value for sale_record_info.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.platform
     *
     * @return the value of sale_record_info.platform
     *
     * @mbg.generated
     */
    public Byte getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.platform
     *
     * @param platform the value for sale_record_info.platform
     *
     * @mbg.generated
     */
    public void setPlatform(Byte platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.bid_price
     *
     * @return the value of sale_record_info.bid_price
     *
     * @mbg.generated
     */
    public Integer getBidPrice() {
        return bidPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.bid_price
     *
     * @param bidPrice the value for sale_record_info.bid_price
     *
     * @mbg.generated
     */
    public void setBidPrice(Integer bidPrice) {
        this.bidPrice = bidPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.tech_service_fee
     *
     * @return the value of sale_record_info.tech_service_fee
     *
     * @mbg.generated
     */
    public Integer getTechServiceFee() {
        return techServiceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.tech_service_fee
     *
     * @param techServiceFee the value for sale_record_info.tech_service_fee
     *
     * @mbg.generated
     */
    public void setTechServiceFee(Integer techServiceFee) {
        this.techServiceFee = techServiceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.transfer_service_fee
     *
     * @return the value of sale_record_info.transfer_service_fee
     *
     * @mbg.generated
     */
    public Integer getTransferServiceFee() {
        return transferServiceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.transfer_service_fee
     *
     * @param transferServiceFee the value for sale_record_info.transfer_service_fee
     *
     * @mbg.generated
     */
    public void setTransferServiceFee(Integer transferServiceFee) {
        this.transferServiceFee = transferServiceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.operate_service_fee
     *
     * @return the value of sale_record_info.operate_service_fee
     *
     * @mbg.generated
     */
    public Integer getOperateServiceFee() {
        return operateServiceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.operate_service_fee
     *
     * @param operateServiceFee the value for sale_record_info.operate_service_fee
     *
     * @mbg.generated
     */
    public void setOperateServiceFee(Integer operateServiceFee) {
        this.operateServiceFee = operateServiceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.postage_fee
     *
     * @return the value of sale_record_info.postage_fee
     *
     * @mbg.generated
     */
    public Integer getPostageFee() {
        return postageFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.postage_fee
     *
     * @param postageFee the value for sale_record_info.postage_fee
     *
     * @mbg.generated
     */
    public void setPostageFee(Integer postageFee) {
        this.postageFee = postageFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.discount_fee
     *
     * @return the value of sale_record_info.discount_fee
     *
     * @mbg.generated
     */
    public Integer getDiscountFee() {
        return discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.discount_fee
     *
     * @param discountFee the value for sale_record_info.discount_fee
     *
     * @mbg.generated
     */
    public void setDiscountFee(Integer discountFee) {
        this.discountFee = discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.estimate_price
     *
     * @return the value of sale_record_info.estimate_price
     *
     * @mbg.generated
     */
    public Integer getEstimatePrice() {
        return estimatePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.estimate_price
     *
     * @param estimatePrice the value for sale_record_info.estimate_price
     *
     * @mbg.generated
     */
    public void setEstimatePrice(Integer estimatePrice) {
        this.estimatePrice = estimatePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.actual_price
     *
     * @return the value of sale_record_info.actual_price
     *
     * @mbg.generated
     */
    public Integer getActualPrice() {
        return actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.actual_price
     *
     * @param actualPrice the value for sale_record_info.actual_price
     *
     * @mbg.generated
     */
    public void setActualPrice(Integer actualPrice) {
        this.actualPrice = actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.buyer_name
     *
     * @return the value of sale_record_info.buyer_name
     *
     * @mbg.generated
     */
    public String getBuyerName() {
        return buyerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.buyer_name
     *
     * @param buyerName the value for sale_record_info.buyer_name
     *
     * @mbg.generated
     */
    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName == null ? null : buyerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.buyer_address
     *
     * @return the value of sale_record_info.buyer_address
     *
     * @mbg.generated
     */
    public String getBuyerAddress() {
        return buyerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.buyer_address
     *
     * @param buyerAddress the value for sale_record_info.buyer_address
     *
     * @mbg.generated
     */
    public void setBuyerAddress(String buyerAddress) {
        this.buyerAddress = buyerAddress == null ? null : buyerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.buyer_mobile
     *
     * @return the value of sale_record_info.buyer_mobile
     *
     * @mbg.generated
     */
    public String getBuyerMobile() {
        return buyerMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.buyer_mobile
     *
     * @param buyerMobile the value for sale_record_info.buyer_mobile
     *
     * @mbg.generated
     */
    public void setBuyerMobile(String buyerMobile) {
        this.buyerMobile = buyerMobile == null ? null : buyerMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.express_carrier
     *
     * @return the value of sale_record_info.express_carrier
     *
     * @mbg.generated
     */
    public Byte getExpressCarrier() {
        return expressCarrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.express_carrier
     *
     * @param expressCarrier the value for sale_record_info.express_carrier
     *
     * @mbg.generated
     */
    public void setExpressCarrier(Byte expressCarrier) {
        this.expressCarrier = expressCarrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.send_time
     *
     * @return the value of sale_record_info.send_time
     *
     * @mbg.generated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.send_time
     *
     * @param sendTime the value for sale_record_info.send_time
     *
     * @mbg.generated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.has_received_flag
     *
     * @return the value of sale_record_info.has_received_flag
     *
     * @mbg.generated
     */
    public Byte getHasReceivedFlag() {
        return hasReceivedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.has_received_flag
     *
     * @param hasReceivedFlag the value for sale_record_info.has_received_flag
     *
     * @mbg.generated
     */
    public void setHasReceivedFlag(Byte hasReceivedFlag) {
        this.hasReceivedFlag = hasReceivedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.received_time
     *
     * @return the value of sale_record_info.received_time
     *
     * @mbg.generated
     */
    public Date getReceivedTime() {
        return receivedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.received_time
     *
     * @param receivedTime the value for sale_record_info.received_time
     *
     * @mbg.generated
     */
    public void setReceivedTime(Date receivedTime) {
        this.receivedTime = receivedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.is_del
     *
     * @return the value of sale_record_info.is_del
     *
     * @mbg.generated
     */
    public Byte getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.is_del
     *
     * @param isDel the value for sale_record_info.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Byte isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.create_time
     *
     * @return the value of sale_record_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.create_time
     *
     * @param createTime the value for sale_record_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_record_info.modify_time
     *
     * @return the value of sale_record_info.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_record_info.modify_time
     *
     * @param modifyTime the value for sale_record_info.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}