package com.russellzhou.trade.data.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table spider_info
 */
public class SpiderInfo {
    /**
     * Database Column Remarks:
     *   主键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   spu编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.spu_id
     *
     * @mbg.generated
     */
    private Long spuId;

    /**
     * Database Column Remarks:
     *   商品编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.sku_id
     *
     * @mbg.generated
     */
    private Long skuId;

    /**
     * Database Column Remarks:
     *   数据来源站点
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.web_channel
     *
     * @mbg.generated
     */
    private String webChannel;

    /**
     * Database Column Remarks:
     *   商品品牌
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.sku_brand
     *
     * @mbg.generated
     */
    private String skuBrand;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.sku_title
     *
     * @mbg.generated
     */
    private String skuTitle;

    /**
     * Database Column Remarks:
     *   商品类别，鞋、衣服等
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.sku_type
     *
     * @mbg.generated
     */
    private Byte skuType;

    /**
     * Database Column Remarks:
     *   商品尺码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.sku_size
     *
     * @mbg.generated
     */
    private String skuSize;

    /**
     * Database Column Remarks:
     *   商品尺码单位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.sku_size_unit
     *
     * @mbg.generated
     */
    private String skuSizeUnit;

    /**
     * Database Column Remarks:
     *   商品颜色
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.sku_color
     *
     * @mbg.generated
     */
    private String skuColor;

    /**
     * Database Column Remarks:
     *   商品图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.sku_img
     *
     * @mbg.generated
     */
    private String skuImg;

    /**
     * Database Column Remarks:
     *   当前价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.sku_price
     *
     * @mbg.generated
     */
    private Integer skuPrice;

    /**
     * Database Column Remarks:
     *   是否历史最低价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.lowest_price_flag
     *
     * @mbg.generated
     */
    private Byte lowestPriceFlag;

    /**
     * Database Column Remarks:
     *   Sku购买链接
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.sku_pruchase_url
     *
     * @mbg.generated
     */
    private String skuPruchaseUrl;

    /**
     * Database Column Remarks:
     *   Spu购买链接
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.spu_purchase_url
     *
     * @mbg.generated
     */
    private String spuPurchaseUrl;

    /**
     * Database Column Remarks:
     *   适用性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.sex
     *
     * @mbg.generated
     */
    private Byte sex;

    /**
     * Database Column Remarks:
     *   是否是成人款
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.adult_flag
     *
     * @mbg.generated
     */
    private Byte adultFlag;

    /**
     * Database Column Remarks:
     *   店铺编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.store_id
     *
     * @mbg.generated
     */
    private Long storeId;

    /**
     * Database Column Remarks:
     *   店铺名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.store_name
     *
     * @mbg.generated
     */
    private String storeName;

    /**
     * Database Column Remarks:
     *   当前店铺是否存在优惠
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.store_has_discount_flag
     *
     * @mbg.generated
     */
    private Byte storeHasDiscountFlag;

    /**
     * Database Column Remarks:
     *   店铺链接
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.store_url
     *
     * @mbg.generated
     */
    private String storeUrl;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.is_del
     *
     * @mbg.generated
     */
    private Byte isDel;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spider_info.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.id
     *
     * @return the value of spider_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.id
     *
     * @param id the value for spider_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.spu_id
     *
     * @return the value of spider_info.spu_id
     *
     * @mbg.generated
     */
    public Long getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.spu_id
     *
     * @param spuId the value for spider_info.spu_id
     *
     * @mbg.generated
     */
    public void setSpuId(Long spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.sku_id
     *
     * @return the value of spider_info.sku_id
     *
     * @mbg.generated
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.sku_id
     *
     * @param skuId the value for spider_info.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.web_channel
     *
     * @return the value of spider_info.web_channel
     *
     * @mbg.generated
     */
    public String getWebChannel() {
        return webChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.web_channel
     *
     * @param webChannel the value for spider_info.web_channel
     *
     * @mbg.generated
     */
    public void setWebChannel(String webChannel) {
        this.webChannel = webChannel == null ? null : webChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.sku_brand
     *
     * @return the value of spider_info.sku_brand
     *
     * @mbg.generated
     */
    public String getSkuBrand() {
        return skuBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.sku_brand
     *
     * @param skuBrand the value for spider_info.sku_brand
     *
     * @mbg.generated
     */
    public void setSkuBrand(String skuBrand) {
        this.skuBrand = skuBrand == null ? null : skuBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.sku_title
     *
     * @return the value of spider_info.sku_title
     *
     * @mbg.generated
     */
    public String getSkuTitle() {
        return skuTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.sku_title
     *
     * @param skuTitle the value for spider_info.sku_title
     *
     * @mbg.generated
     */
    public void setSkuTitle(String skuTitle) {
        this.skuTitle = skuTitle == null ? null : skuTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.sku_type
     *
     * @return the value of spider_info.sku_type
     *
     * @mbg.generated
     */
    public Byte getSkuType() {
        return skuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.sku_type
     *
     * @param skuType the value for spider_info.sku_type
     *
     * @mbg.generated
     */
    public void setSkuType(Byte skuType) {
        this.skuType = skuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.sku_size
     *
     * @return the value of spider_info.sku_size
     *
     * @mbg.generated
     */
    public String getSkuSize() {
        return skuSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.sku_size
     *
     * @param skuSize the value for spider_info.sku_size
     *
     * @mbg.generated
     */
    public void setSkuSize(String skuSize) {
        this.skuSize = skuSize == null ? null : skuSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.sku_size_unit
     *
     * @return the value of spider_info.sku_size_unit
     *
     * @mbg.generated
     */
    public String getSkuSizeUnit() {
        return skuSizeUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.sku_size_unit
     *
     * @param skuSizeUnit the value for spider_info.sku_size_unit
     *
     * @mbg.generated
     */
    public void setSkuSizeUnit(String skuSizeUnit) {
        this.skuSizeUnit = skuSizeUnit == null ? null : skuSizeUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.sku_color
     *
     * @return the value of spider_info.sku_color
     *
     * @mbg.generated
     */
    public String getSkuColor() {
        return skuColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.sku_color
     *
     * @param skuColor the value for spider_info.sku_color
     *
     * @mbg.generated
     */
    public void setSkuColor(String skuColor) {
        this.skuColor = skuColor == null ? null : skuColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.sku_img
     *
     * @return the value of spider_info.sku_img
     *
     * @mbg.generated
     */
    public String getSkuImg() {
        return skuImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.sku_img
     *
     * @param skuImg the value for spider_info.sku_img
     *
     * @mbg.generated
     */
    public void setSkuImg(String skuImg) {
        this.skuImg = skuImg == null ? null : skuImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.sku_price
     *
     * @return the value of spider_info.sku_price
     *
     * @mbg.generated
     */
    public Integer getSkuPrice() {
        return skuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.sku_price
     *
     * @param skuPrice the value for spider_info.sku_price
     *
     * @mbg.generated
     */
    public void setSkuPrice(Integer skuPrice) {
        this.skuPrice = skuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.lowest_price_flag
     *
     * @return the value of spider_info.lowest_price_flag
     *
     * @mbg.generated
     */
    public Byte getLowestPriceFlag() {
        return lowestPriceFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.lowest_price_flag
     *
     * @param lowestPriceFlag the value for spider_info.lowest_price_flag
     *
     * @mbg.generated
     */
    public void setLowestPriceFlag(Byte lowestPriceFlag) {
        this.lowestPriceFlag = lowestPriceFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.sku_pruchase_url
     *
     * @return the value of spider_info.sku_pruchase_url
     *
     * @mbg.generated
     */
    public String getSkuPruchaseUrl() {
        return skuPruchaseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.sku_pruchase_url
     *
     * @param skuPruchaseUrl the value for spider_info.sku_pruchase_url
     *
     * @mbg.generated
     */
    public void setSkuPruchaseUrl(String skuPruchaseUrl) {
        this.skuPruchaseUrl = skuPruchaseUrl == null ? null : skuPruchaseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.spu_purchase_url
     *
     * @return the value of spider_info.spu_purchase_url
     *
     * @mbg.generated
     */
    public String getSpuPurchaseUrl() {
        return spuPurchaseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.spu_purchase_url
     *
     * @param spuPurchaseUrl the value for spider_info.spu_purchase_url
     *
     * @mbg.generated
     */
    public void setSpuPurchaseUrl(String spuPurchaseUrl) {
        this.spuPurchaseUrl = spuPurchaseUrl == null ? null : spuPurchaseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.sex
     *
     * @return the value of spider_info.sex
     *
     * @mbg.generated
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.sex
     *
     * @param sex the value for spider_info.sex
     *
     * @mbg.generated
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.adult_flag
     *
     * @return the value of spider_info.adult_flag
     *
     * @mbg.generated
     */
    public Byte getAdultFlag() {
        return adultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.adult_flag
     *
     * @param adultFlag the value for spider_info.adult_flag
     *
     * @mbg.generated
     */
    public void setAdultFlag(Byte adultFlag) {
        this.adultFlag = adultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.store_id
     *
     * @return the value of spider_info.store_id
     *
     * @mbg.generated
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.store_id
     *
     * @param storeId the value for spider_info.store_id
     *
     * @mbg.generated
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.store_name
     *
     * @return the value of spider_info.store_name
     *
     * @mbg.generated
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.store_name
     *
     * @param storeName the value for spider_info.store_name
     *
     * @mbg.generated
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.store_has_discount_flag
     *
     * @return the value of spider_info.store_has_discount_flag
     *
     * @mbg.generated
     */
    public Byte getStoreHasDiscountFlag() {
        return storeHasDiscountFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.store_has_discount_flag
     *
     * @param storeHasDiscountFlag the value for spider_info.store_has_discount_flag
     *
     * @mbg.generated
     */
    public void setStoreHasDiscountFlag(Byte storeHasDiscountFlag) {
        this.storeHasDiscountFlag = storeHasDiscountFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.store_url
     *
     * @return the value of spider_info.store_url
     *
     * @mbg.generated
     */
    public String getStoreUrl() {
        return storeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.store_url
     *
     * @param storeUrl the value for spider_info.store_url
     *
     * @mbg.generated
     */
    public void setStoreUrl(String storeUrl) {
        this.storeUrl = storeUrl == null ? null : storeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.is_del
     *
     * @return the value of spider_info.is_del
     *
     * @mbg.generated
     */
    public Byte getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.is_del
     *
     * @param isDel the value for spider_info.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Byte isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.create_time
     *
     * @return the value of spider_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.create_time
     *
     * @param createTime the value for spider_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spider_info.modify_time
     *
     * @return the value of spider_info.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spider_info.modify_time
     *
     * @param modifyTime the value for spider_info.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}