package com.russellzhou.trade.data.dao;

import com.russellzhou.trade.data.entity.InventoryInfo;

public interface InventoryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String inventoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_info
     *
     * @mbg.generated
     */
    int insert(InventoryInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_info
     *
     * @mbg.generated
     */
    int insertSelective(InventoryInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_info
     *
     * @mbg.generated
     */
    InventoryInfo selectByPrimaryKey(String inventoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InventoryInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InventoryInfo row);
}