package com.russellzhou.trade.data.dao;

import com.russellzhou.trade.data.entity.SaleRecordInfo;

public interface SaleRecordInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_record_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String saleRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_record_info
     *
     * @mbg.generated
     */
    int insert(SaleRecordInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_record_info
     *
     * @mbg.generated
     */
    int insertSelective(SaleRecordInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_record_info
     *
     * @mbg.generated
     */
    SaleRecordInfo selectByPrimaryKey(String saleRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_record_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SaleRecordInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_record_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SaleRecordInfo row);
}