package com.russellzhou.trade.data.dao;

import com.russellzhou.trade.data.entity.SpiderInfo;

public interface SpiderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_info
     *
     * @mbg.generated
     */
    int insert(SpiderInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_info
     *
     * @mbg.generated
     */
    int insertSelective(SpiderInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_info
     *
     * @mbg.generated
     */
    SpiderInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SpiderInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SpiderInfo row);
}