package com.russellzhou.trade.data.dao;

import com.russellzhou.trade.data.entity.spiderInfo;

public interface spiderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_info
     *
     * @mbg.generated
     */
    int insert(spiderInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_info
     *
     * @mbg.generated
     */
    int insertSelective(spiderInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_info
     *
     * @mbg.generated
     */
    spiderInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(spiderInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spider_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(spiderInfo row);
}